import { CharacterConfig, BoardConfig } from '../types/game';

export const CHARACTERS: CharacterConfig[] = [
  {
    id: 'street_runner',
    name: 'Dash 达许',
    title: '街头滑手',
    cost: 0,
    unlocked: true,
    modelType: 'street_runner',
    description: '敏捷灵动的街头极限少年，擅长穿梭于城市车流与轨道之间。',
    colorScheme: {
      primary: '#00e5ff',
      secondary: '#1a1f38',
      glow: '#00ffff',
      hair: '#ff6600',
      skin: '#f5c6a5',
    },
    skillName: '超频冲锋',
    skillDesc: '瞬间爆发推进力，无敌冲刺3秒并自动吸取沿途金币。',
    skillCooldown: 25,
    passiveBonus: '磁铁拾取范围 +30%',
  },
  {
    id: 'cyber_ninja',
    name: 'Neon 疾刃',
    title: '赛博忍者',
    cost: 2500,
    unlocked: false,
    modelType: 'cyber_ninja',
    description: '暗夜霓虹中的影武者，手持等离子光刃，动作迅如雷霆。',
    colorScheme: {
      primary: '#ff007f',
      secondary: '#0f0f1b',
      glow: '#ff00bb',
      hair: '#ffffff',
      skin: '#e0c0a8',
    },
    skillName: '瞬影斩空',
    skillDesc: '向前方瞬间折跃冲刺，斩断并清除前方全部障碍物。',
    skillCooldown: 22,
    passiveBonus: '二段跳可进行360°旋风翻滚，空中滞空更久',
  },
  {
    id: 'astro_nova',
    name: 'Astro 诺娃',
    title: '星际行者',
    cost: 5000,
    unlocked: false,
    modelType: 'astro_nova',
    description: '来自深空科考站的探险家，装备微型反重力动力喷射背包。',
    colorScheme: {
      primary: '#7928ca',
      secondary: '#0c0e29',
      glow: '#00f0ff',
      hair: '#00ffff',
      skin: '#f0d0b8',
    },
    skillName: '引力浮空',
    skillDesc: '启动反重力推进器升空巡航5秒，生成高空专属金币星轨。',
    skillCooldown: 30,
    passiveBonus: '喷气背包拾取时额外延长4秒飞行时间',
  },
  {
    id: 'shrine_fox',
    name: 'Akira 绯夜',
    title: '神域巫女',
    cost: 8000,
    unlocked: false,
    modelType: 'shrine_fox',
    description: '掌管千本鸟居结界的灵狐巫女，御使灵火守护跑者平安。',
    colorScheme: {
      primary: '#ff3344',
      secondary: '#ffffff',
      glow: '#ffaa00',
      hair: '#2a1a24',
      skin: '#fae1d0',
    },
    skillName: '灵狐结界',
    skillDesc: '展开环绕周身的神圣狐火护盾，免疫一次撞击并将障碍化为金币。',
    skillCooldown: 35,
    passiveBonus: '所有增益道具持续时间 +25%',
  },
  {
    id: 'mecha_rex',
    name: 'Rex 金甲暴龙',
    title: '量子机械师',
    cost: 15000,
    unlocked: false,
    modelType: 'mecha_rex',
    description: '全身钛金与能量管道驱动的高阶仿生改造人，得分机器。',
    colorScheme: {
      primary: '#ffd700',
      secondary: '#1e1e24',
      glow: '#ffaa00',
      hair: '#444444',
      skin: '#d4af37',
    },
    skillName: '量子过载',
    skillDesc: '释放全域引力磁暴吸光视野内金币，并进入6秒5倍狂热得分！',
    skillCooldown: 40,
    passiveBonus: '跑酷基础得分倍率永久 +5x',
  },
];

export const BOARDS: BoardConfig[] = [
  {
    id: 'neon_classic',
    name: 'Neon Cruiser 荧光巡航',
    cost: 0,
    unlocked: true,
    color: '#00f0ff',
    glowColor: '#00ffff',
    trailColor: '#00e5ff',
    perkDesc: '经典能量滑板，双击呼出。碰撞时保护玩家免受一次致命失误。',
    speedBoost: 1.15,
  },
  {
    id: 'plasma_hover',
    name: 'Plasma Wing 离子飞翼',
    cost: 2000,
    unlocked: false,
    color: '#ff00aa',
    glowColor: '#ff00ff',
    trailColor: '#ff33bb',
    perkDesc: '搭载等离子悬浮翼，滑板状态下赋予【三段跳】与超强滞空滑翔！',
    speedBoost: 1.25,
  },
  {
    id: 'inferno_comet',
    name: 'Inferno Comet 炽热彗星',
    cost: 4500,
    unlocked: false,
    color: '#ff5500',
    glowColor: '#ffaa00',
    trailColor: '#ff3300',
    perkDesc: '释放超高温彗星烈焰尾迹，高速行驶可直接撞碎低矮路障！',
    speedBoost: 1.35,
  },
  {
    id: 'cyber_gold',
    name: 'Quantum Midas 量子点金',
    cost: 9000,
    unlocked: false,
    color: '#ffd700',
    glowColor: '#ffe600',
    trailColor: '#ffcc00',
    perkDesc: '量子炼金阵列，滑板激活期间所拾取的所有金币价值翻倍 (x2)！',
    speedBoost: 1.2,
  },
];

export const INITIAL_MISSIONS = [
  {
    id: 'm1',
    title: '初入赛道',
    description: '单局单次跳跃超过 8 次',
    progress: 0,
    target: 8,
    rewardCoins: 200,
    rewardKeys: 1,
    completed: false,
    claimed: false,
    type: 'jump' as const,
  },
  {
    id: 'm2',
    title: '极限滑铲',
    description: '单局滑行穿过 5 个障碍物',
    progress: 0,
    target: 5,
    rewardCoins: 300,
    rewardKeys: 1,
    completed: false,
    claimed: false,
    type: 'slide' as const,
  },
  {
    id: 'm3',
    title: '空中特技',
    description: '单局完成 4 次空中二段跳翻滚',
    progress: 0,
    target: 4,
    rewardCoins: 350,
    rewardKeys: 1,
    completed: false,
    claimed: false,
    type: 'double_jump' as const,
  },
  {
    id: 'm4',
    title: '赏金猎手',
    description: '单局收集 150 枚金币',
    progress: 0,
    target: 150,
    rewardCoins: 400,
    rewardKeys: 2,
    completed: false,
    claimed: false,
    type: 'coins' as const,
  },
  {
    id: 'm5',
    title: '千里疾驰',
    description: '单局奔跑距离达到 1000 米',
    progress: 0,
    target: 1000,
    rewardCoins: 600,
    rewardKeys: 2,
    completed: false,
    claimed: false,
    type: 'distance' as const,
  },
  {
    id: 'm6',
    title: '高分霸主',
    description: '单局得分突破 10,000 分',
    progress: 0,
    target: 10000,
    rewardCoins: 800,
    rewardKeys: 3,
    completed: false,
    claimed: false,
    type: 'score' as const,
  },
];
